services:
  - type: web
    name: taskmanager
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        sync: false
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://your-placeholder.onrender.com
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: sql.freesqldatabase.com
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: your_db_name
      - key: DB_USERNAME
        value: your_db_username
      - key: DB_PASSWORD
        value: your_db_password
      - key: SESSION_DRIVER
        value: database
      - key: QUEUE_CONNECTION
        value: database
      - key: VITE_APP_NAME
        value: Laravel
